### ISSUE TITLE
Refactor current code based on expected plans

### ISSUE THREAD

**Issue by sbeleidy** [PEERbots/peerbots-content#88]
Based on our current understanding of the features we plan to incorporate in the next build, we should refactor the current code to make sure that future work is relatively straightforward.

This issue should include basic refactoring that we would want to do now that we've had some time away from the codebase and are approaching it with fresh eyes again.

**Comment by ynadeem** [comment]
Based on my initial review of the codebase, I don't think there is anything major that requires a refactor so we are going to close this issue.
